# OpenAPI spec for qbo-bridge
openapi: 3.0.3
info:
  title: qbo-bridge
  version: 0.3.2
  description: Minimal bridge to QuickBooks Online for GPT Actions
servers:
  - url: https://accounting-qbo.onrender.com
components:
  securitySchemes:
    actionApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
  schemas:
    QboResponse:
      type: object
      additionalProperties: true
    ConnectionStatus:
      type: object
      properties:
        connected:
          type: boolean
        realmId:
          type: string
          nullable: true
        userId:
          type: string
          nullable: true
        expires:
          type: integer
          nullable: true
          description: Epoch seconds
        expiresInSec:
          type: integer
          nullable: true
      required:
        - connected
security:
  - actionApiKey: []
  - bearerAuth: []
paths:
  /qbo/query:
    get:
      summary: Run a QuickBooks query
      operationId: qboQuery
      parameters:
        - in: query
          name: realmId
          required: false
          schema:
            type: string
          description: Optional; defaults to the connected company.
        - in: query
          name: q
          required: true
          schema:
            type: string
      responses:
        '200':
          description: QBO query response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QboResponse'

  /qbo/purchase:
    post:
      summary: Create a Purchase transaction
      operationId: createPurchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                realmId:
                  type: string
                  description: Optional; defaults to the connected company.
                paymentType:
                  type: string
                  enum: [Cash, CreditCard]
                accountRef:
                  type: object
                  properties:
                    value:
                      type: string
                  required:
                    - value
                vendorRef:
                  type: object
                  properties:
                    value:
                      type: string
                  required:
                    - value
                  description: Provide either vendorRef or vendorName.
                vendorName:
                  type: string
                  description: If set (and vendorRef omitted), the API upserts the vendor by DisplayName before creating the Purchase.
                txnDate:
                  type: string
                  pattern: '^\d{4}-\d{2}-\d{2}$'
                privateNote:
                  type: string
                lines:
                  type: array
                  items:
                    type: object
                    properties:
                      amount:
                        type: number
                      description:
                        type: string
                      expenseAccountRef:
                        type: object
                        properties:
                          value:
                            type: string
                        required:
                          - value
                      expenseAccountName:
                        type: string
                        description: If provided (and expenseAccountRef omitted), the API upserts an Expense account (detail Supplies) and uses it.
                      customerRef:
                        type: object
                        properties:
                          value:
                            type: string
                      classRef:
                        type: object
                        properties:
                          value:
                            type: string
                      taxCodeRef:
                        type: object
                        properties:
                          value:
                            type: string
                      billableStatus:
                        type: string
                        enum: [NotBillable, Billable]
                  minItems: 1
              required:
                - paymentType
                - accountRef
                - txnDate
                - lines
      responses:
        '200':
          description: QBO create purchase response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QboResponse'

  /qbo/attachment:
    post:
      summary: Upload an attachment and link to a Purchase
      operationId: uploadAttachment
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                realmId:
                  type: string
                  description: Optional; defaults to the connected company.
                txnId:
                  type: string
                note:
                  type: string
                file:
                  type: string
                  format: binary
              required:
                - txnId
                - file
      responses:
        '200':
          description: QBO upload response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QboResponse'

  /lookups/vendors:
    get:
      summary: List vendors (optionally filtered by name)
      operationId: listVendors
      parameters:
        - in: query
          name: realmId
          required: false
          schema:
            type: string
          description: Optional; defaults to the connected company.
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Optional filter; matches anywhere in DisplayName.
      responses:
        '200':
          description: Vendors list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QboResponse'

  /lookups/accounts:
    get:
      summary: List accounts (optionally filtered by name)
      operationId: listAccounts
      parameters:
        - in: query
          name: realmId
          required: false
          schema:
            type: string
          description: Optional; defaults to the connected company.
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Optional filter; matches anywhere in Name.
      responses:
        '200':
          description: Accounts list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QboResponse'

  /lookups/customers:
    get:
      summary: List customers (optionally filtered by name)
      operationId: listCustomers
      parameters:
        - in: query
          name: realmId
          required: false
          schema:
            type: string
          description: Optional; defaults to the connected company.
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Optional filter; matches anywhere in DisplayName.
      responses:
        '200':
          description: Customers list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QboResponse'

  /oauth/status:
    get:
      summary: Connection status (debug)
      description: Returns whether a QuickBooks company is connected and the current realm information.
      operationId: oauthStatus
      security: []
      responses:
        '200':
          description: Current connection status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionStatus'

  /qbo/vendor:
    post:
      summary: Upsert a vendor by DisplayName
      operationId: upsertVendor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                realmId:
                  type: string
                  description: Optional; defaults to the connected company.
                displayName:
                  type: string
                email:
                  type: string
                  format: email
                phone:
                  type: string
                billAddr:
                  type: object
                  properties:
                    Line1:
                      type: string
                    City:
                      type: string
                    CountrySubDivisionCode:
                      type: string
                    PostalCode:
                      type: string
              required:
                - displayName
      responses:
        '200':
          description: Vendor upsert response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Vendor:
                    type: object
                    properties:
                      Id:
                        type: string
                      DisplayName:
                        type: string

  /qbo/account:
    post:
      summary: Upsert an account by Name (defaults to Expense/Supplies)
      operationId: upsertAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                realmId:
                  type: string
                  description: Optional; defaults to the connected company.
                name:
                  type: string
                type:
                  type: string
                  description: Default Expense
                detailType:
                  type: string
                  description: Default Supplies
                parentRef:
                  type: object
                  properties:
                    value:
                      type: string
              required:
                - name
      responses:
        '200':
          description: Account upsert response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Account:
                    type: object
                    properties:
                      Id:
                        type: string
                      Name:
                        type: string
                      AccountType:
                        type: string

# Note for ChatGPT OAuth setup (not part of the spec):
# Authorization URL: https://appcenter.intuit.com/connect/oauth2
# Token URL: https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer
# Scopes: com.intuit.quickbooks.accounting

